In [100]:
import numpy as np
import pandas as pd

# reading in file and creating a dataframe for the data in that file
df = pd.read_csv('Telco-Customer-Churn.csv')

# sanity check to make sure my file was imported correctly 
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [101]:
# checking data type of TotalCharges
print(df['TotalCharges'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: TotalCharges
Non-Null Count  Dtype
--------------  -----
7043 non-null   object
dtypes: object(1)
memory usage: 55.1+ KB
None

In [102]:
# checking for any blank cells in TotalCharges
df[df['TotalCharges'] == ' ']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [103]:
# after checking, we found some blank entries
# these entries were due to specific customers having a tenure of 0
# so this means they literally just signed up
# instead of deleting these rows, I will assign all customers with tenure = 0 AND TotalCharges = " " to have a TotalCharges = 0 instead
df.loc[(df['tenure'] == 0) & (df['TotalCharges'] == ' '), 'TotalCharges'] = 0

# after doing this, I will change all values in this column to be numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])

# sanity check
df[df['TotalCharges'] == ' ']
print(df['TotalCharges'].info())

<class 'pandas.core.series.Series'>
RangeIndex: 7043 entries, 0 to 7042
Series name: TotalCharges
Non-Null Count  Dtype
--------------  -----
7043 non-null   float64
dtypes: float64(1)
memory usage: 55.1 KB
None

In [104]:
# i will change all values in my churn columns
# Yes -> 1, No -> 0
df['Churn'] = np.where(df['Churn'] == 'Yes',  1, 0)

# sanity check
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [105]:
# creating new column Tenure_Cohort
# will do the following grouping:
# 0-12 Months | 13-24 Months | 25-48 Months | Over 48 Months

bins = [0, 12, 24, 48, np.inf]
labels = ['0-12 Months', '13-24 Months', '25-48 Months', 'Over 48 Months']

Tenure_Cohort = pd.cut(df['tenure'], bins = bins, labels = labels)
print(Tenure_Cohort)

df['Tenure_Cohort'] = Tenure_Cohort
df.head()

0          0-12 Months
1         25-48 Months
2          0-12 Months
3         25-48 Months
4          0-12 Months
             ...
7038      13-24 Months
7039    Over 48 Months
7040       0-12 Months
7041       0-12 Months
7042    Over 48 Months
Name: tenure, Length: 7043, dtype: category
Categories (4, object): ['0-12 Months' < '13-24 Months' < '25-48 Months' < 'Over 48 Months']

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Tenure_Cohort
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0-12 Months
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,0,25-48 Months
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,0-12 Months
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,25-48 Months
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,0-12 Months

In [106]:
df_copy = df.copy()
df_copy = df_copy.drop(columns='customerID')
df_copy.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Tenure_Cohort
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0-12 Months
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,No,One year,No,Mailed check,56.95,1889.50,0,25-48 Months
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,0-12 Months
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,25-48 Months
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,0-12 Months

In [107]:
# exporting cleaned data
df_copy.to_csv('cleaned_telco_customer_churn.csv', index=False)

In [108]:
import sqlite3

# creating a temp SQL db in my notebook
conn = sqlite3.connect('churn_analysis.db')

# loading in cleaned df into the SQL db
df_copy.to_sql('customers', conn, if_exists='replace', index=False)

7043

In [ ]:
# writting my SQL queries
# getting the churn average for every customer
query = """
SELECT 
    (ROUND(AVG(Churn) * 100, 2) || '%') AS churn_avg
FROM customers
LIMIT 10
"""

pd.read_sql(query, conn)

  churn_avg
0    26.54%

In [121]:
# calculating average by contract type
query = """
SELECT
    Contract, 
    COUNT(*) AS total_customers, 
    (ROUND(AVG(Churn) * 100, 2) || '%') AS churn_avg
FROM
    customers
GROUP BY 
    Contract
ORDER BY 
    AVG(Churn) DESC
"""

pd.read_sql(query, conn)

         Contract  total_customers churn_avg
0  Month-to-month             3875    42.71%
1        One year             1473    11.27%
2        Two year             1695     2.83%

In [125]:
# calculating average by Tenure_Cohort
# we want to see if the longer a customer stays, the less likely they are to cancel.
query = """
SELECT
    Tenure_Cohort, 
    COUNT(*) AS total_customers,
    (ROUND(AVG(Churn) * 100, 2) || '%') AS churn_avg
FROM
    customers
GROUP BY 
    Tenure_Cohort
ORDER BY 
    AVG(Churn) DESC
"""

pd.read_sql(query, conn)

    Tenure_Cohort  total_customers churn_avg
0     0-12 Months             2175    47.68%
1    13-24 Months             1024    28.71%
2    25-48 Months             1594    20.39%
3  Over 48 Months             2239     9.51%
4            None               11      0.0%

In [129]:
# writting a query to look at the highest-risk group (Month-to-Month users) 
# and see if having TechSupport makes them stay longer.
query = """
SELECT 
    Contract,
    TechSupport, 
    COUNT(*) AS total_customers, 
    (ROUND(AVG(Churn) * 100, 2) || '%') AS churn_avg
FROM 
    customers
WHERE
    Contract = 'Month-to-month'
GROUP BY 
    TechSupport
ORDER BY 
    AVG(Churn) DESC
"""

pd.read_sql(query, conn)

         Contract          TechSupport  total_customers churn_avg
0  Month-to-month                   No             2680    50.37%
1  Month-to-month                  Yes              671     30.7%
2  Month-to-month  No internet service              524    18.89%